### ISSUE TITLE
Compile/Instal Charabia on openBSD

### ISSUE THREAD

**Issue by sandeep-gh** [meilisearch/charabia#118]
I am on openBSD running on Raspberry Pi 4. I am unable to install meilisearch due to cargo not able to find charabia. So i decided to 
compile from source. 
I downloaded the source from github and did "cargo run' in the charabia source code. I get the error: 
```
error: failed to parse manifest at `/home/kabira/LibOpenSource/charabia/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
```
Any workaround suggesting would be great.

**Comment by irevoire** [comment]
Look like you need to update your rust version :unamused:

**Comment by curquiza** [comment]
Hello @sandeep-gh!
Have you fixed your issue?

**Comment by sandeep-gh** [comment]
Hello,

I am still figuring out how o upgrade to latest rust on openBSD. It is not
straightforward at all.
I will give it another going sometime next week. Will let know.

Thanks.
-S

**Comment by curquiza** [comment]
Ok, I close this issue since it does not seem to be something we can handle on our side
If this is something we can fix, please let us know, I will re-open the issue!
