### ISSUE TITLE
Latin script: Segmenter should split camelCased words

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#129]
Today, Meilisearch is splitting `snake_case`, `SCREAMING_CASE` and `kebab-case` properly but doesn't split `PascalCase` nor `camelCase`.

### drawback
 Meilisearch doesn't completely support code documentation.

### enhancement
Make Latin Segmenter split camelCased/PascalCase words:
- `"camelCase"` -> `["camel", "Case"]`
- `"PascalCase"` -> `["Pascal", "Case"]`
- `"IJsland"` -> `["IJsland"]` (Language trap)
- `"CASE"` -> `["CASE"]` (another trap)

#### Files expected to be modified
- [/src/segmenter/latin.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/segmenter/latin.rs)

> Hey! 👋 
Before starting any implementation, make sure that you read the [CONTRIBUTING.md](https://github.com/meilisearch/charabia/blob/main/CONTRIBUTING.md#contributing) file.
In addition to the recurrent rules, you can find some guides to easily implement a `Segmenter` or a `Normalizer`.
Thanks a lot for your Contribution! 🤝

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by yenwel** [comment]
@adithyaakrishna  you still doing this otherwise I'd try this next week

**Comment by adithyaakrishna** [comment]
@yenwel I am working on this, as I am very new to rust I have some doubts 😶 

@curquiza Regarding this issue, how about if we convert the string to something which meilisearch already does?

**Comment by ManyTheFish** [comment]
Hey @adithyaakrishna,
you can't convert the String in a segmenter because you don't have ownership of it at this step. So you'll have to find another way to split it.
To help you a bit more, [`split_word_bounds`](https://github.com/meilisearch/charabia/blob/6d0a01d371088283d4e9bbadba24c0a0d2344571/src/segmenter/latin.rs#L12) returns an [`Iterator`](https://doc.rust-lang.org/std/iter/trait.Iterator.html) over `&str`, from this `Iterator` you should be able to re-split each `Item` then flatten it after.

**Comment by ManyTheFish** [comment]
Hey @adithyaakrishna,
any news on this?
Do you need any help? 😄

**Comment by goodhoko** [comment]
Hi!

I have a working patch for this. What's not clear to me is whether we want to keep the whole word or not. I.e. if `camelCase` should be segmented into `["camelCase", "camel", "Case"]` or just `["camel", "Case"]`.

I'd expect the former because if a user searches for `camelCase` we probably want to prioritize documents containing `camelCase` as a whole over documents containing `camel` and `case`. But I'm not familiar with how the ranking at search-time works in Meili so maybe this is handled in some other way.

**Comment by ManyTheFish** [comment]
The goal is to split "camelCase" into ["camel", "Case"] and even "snake_case" into ["snake", "_", "case"].
I agree with you that we will lose precision in favor of the recall, but, in this case, I'd prefer to focus on accent/diacritics precision than on the case. 🤔
