### ISSUE TITLE
Implement a Japanese specialized Normalizer

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#131]
Today, there is no specialized normalizer for the Japanese Language.

### drawback
Meilisearch is unable to find the hiragana version of a word with a katakana query, for instance, `ダメ`, is also spelled `駄目`, or `だめ`

### Technical approach
Create a new Japanese normalizer that unifies hiragana and katakana equivalences.

#### Interesting libraries
- [wana_kana](https://crates.io/crates/wana_kana) seems promising to convert everything in Hiragana

#### Files expected to be modified
- create  [/src/normalizer/japanese.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/normalizer/)
- [/src/normalizer/mod.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/normalizer/mod.rs)

### Misc
related to [product#532](https://github.com/meilisearch/product/discussions/532)

> Hey! 👋 
Before starting any implementation, make sure that you read the [CONTRIBUTING.md](https://github.com/meilisearch/charabia/blob/main/CONTRIBUTING.md#contributing) file.
In addition to the recurrent rules, you can find some guides to easily implement a `Segmenter` or a `Normalizer`.
Thanks a lot for your Contribution! 🤝

**Comment by choznerol** [comment]
> ... for instance, `ダメ`, is also spelled `駄目`, or `だめ`
> ... [wana_kana](https://crates.io/crates/wana_kana) seems promising to convert everything in Hiragana

After some experiments and checking [convert options](https://docs.rs/wana_kana/2.1.0/wana_kana/struct.Options.html), it seems like [wana_kana](https://crates.io/crates/wana_kana) does not support converting Kanji to Hiragana or Romaji. For example:
- `to_hiragana("ダメ駄目だめ")` will be `"だめ駄目だめ"`
- `to_romaji("ダメ駄目だめ")` will be `"dame駄目dame"`

Is it okay if the normalizer only convert Katakana to Hiragana?

**Comment by ManyTheFish** [comment]
Hey @choznerol, the conversion from kanji to Hiragana is not straightforward, that's why all the library I found doesn't support it.
However, converting katakana to hiragana is a great enhancement!

**Comment by mosuka** [comment]
Hi @ManyTheFish @choznerol ,

I think that in Japanese, excessive normalization of katakana and hiragana can create a lot of noise in the opposite direction.
If you wish to treat these hiragana and katakana tokens identically, it is common practice to register the required synonyms in that business domain.

https://docs.meilisearch.com/learn/configuration/synonyms.html

What do you think?

**Comment by mosuka** [comment]
In the normalization of Japanese characters, I think it is more important that I wrote in this comment.
https://github.com/meilisearch/charabia/issues/139#issuecomment-1269247885

**Comment by ManyTheFish** [comment]
thank you @mosuka for your feedback, so let's be cautious. 
I think we will disable this feature on Meilisearch by default and make a prototype enabling it to gather some feedback. 🤔 
On my side, I'll investigate more about the pro and cons of doing this transliteration.
But, keep in mind that we are in an IR context and not in a translation context, sometimes, it is better to lose precision in favor of a higher recall.

**Comment by mosuka** [comment]
@ManyTheFish 
Thank you for your reply.
The above comment is just my personal opinion.
It would be helpful if users could make a choice. :smile: 
Thanks!

**Comment by choznerol** [comment]
Thank @mosuka @ManyTheFish for the discussion. I am afraid I don't have enough Japanese/tokenization knowledge to have input 😅. 

> I think we will disable this feature on Meilisearch by default and make a prototype enabling it to gather some feedback. 🤔

Not sure exactly how this will be implemented, but please let me know if I should also address the "disable by default" part in #149. And of course, if after re-consideration we think #149 is actually too risky, please don't hesitate to close it or leave it pending.

**Comment by ManyTheFish** [comment]
@mosuka @choznerol,
we will merge the PR, but, we have to add a feature flag allowing us to activate or deactivate this normalizer at compile time, instead of depending on the `#[cfg(feature = "japanese")]` for this normalizer we should make it depends on a new flag `#[cfg(feature = "japanese-transliteration")]`.

I requested this last change on your PR @choznerol, everything else is good and should be merged!

Thanks to both of you!
