### ISSUE TITLE
Implement a Compatibility Decomposition Normalizer

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#139]
Meilisearch is unable to find [Canonical and Compatibility equivalences](https://www.unicode.org/reports/tr15/#Canon_Compat_Equivalence), for instance, `ｶﾞｷﾞｸﾞｹﾞｺﾞ` can't be found with a query `ガギグゲゴ`.

### Technical approach
Implement a new Normalizer `CompatibilityDecompositionNormalizer` using the method [`nfkd`](https://docs.rs/unicode-normalization/0.1.22/unicode_normalization/trait.UnicodeNormalization.html#tymethod.nfkd) of the [unicode-normalization](https://crates.io/crates/unicode-normalization) crate.

#### Files expected to be modified
- create  [/src/normalizer/compatibility_decompostion.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/normalizer/)
- [/src/normalizer/mod.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/normalizer/mod.rs)

### Misc
related to [product#532](https://github.com/meilisearch/product/discussions/532)

> Hey! 👋 
Before starting any implementation, make sure that you read the [CONTRIBUTING.md](https://github.com/meilisearch/charabia/blob/main/CONTRIBUTING.md#contributing) file.
In addition to the recurrent rules, you can find some guides to easily implement a `Segmenter` or a `Normalizer`.
Thanks a lot for your Contribution! 🤝

**Comment by mosuka** [comment]
@ManyTheFish 
Thank you for the creating good issue!

This character normalization seems to be performed after tokenization, but in Japanese, some cases it is better to performe character normaliz before tokenization.

For example, this is a case where there is no problem even after tokenization:

```
$ echo "私はメガネを買いました。" | lindera
私	名詞,代名詞,一般,*,*,*,私,ワタシ,ワタシ
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
メガネ	名詞,一般,*,*,*,*,メガネ,メガネ,メガネ
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
買い	動詞,自立,*,*,五段・ワ行促音便,連用形,買う,カイ,カイ
まし	助動詞,*,*,*,特殊・マス,連用形,ます,マシ,マシ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
。	記号,句点,*,*,*,*,。,。,。
EOS
```

```
$ echo "私はﾒｶﾞﾈを買いました。" | lindera
私	名詞,代名詞,一般,*,*,*,私,ワタシ,ワタシ
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
ﾒｶﾞﾈ	UNK
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
買い	動詞,自立,*,*,五段・ワ行促音便,連用形,買う,カイ,カイ
まし	助動詞,*,*,*,特殊・マス,連用形,ます,マシ,マシ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
。	記号,句点,*,*,*,*,。,。,。
EOS
```
Half-width `ﾒｶﾞﾈ` is not a problem because it is tokenized as a single unknown word, although it is not exist in the Japanese morphological dictionary (IPADIC).

But the following cases can be problematic.

```
$ echo "私は時給1000円です。" | lindera
私	名詞,代名詞,一般,*,*,*,私,ワタシ,ワタシ
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
時給	名詞,一般,*,*,*,*,時給,ジキュウ,ジキュー
1000	UNK
円	名詞,接尾,助数詞,*,*,*,円,エン,エン
です	助動詞,*,*,*,特殊・デス,基本形,です,デス,デス
。	記号,句点,*,*,*,*,。,。,。
EOS
```

```
$ echo "私は時給１０００円です。" | lindera
私	名詞,代名詞,一般,*,*,*,私,ワタシ,ワタシ
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
時給	名詞,一般,*,*,*,*,時給,ジキュウ,ジキュー
１	名詞,数,*,*,*,*,１,イチ,イチ
０	名詞,数,*,*,*,*,０,ゼロ,ゼロ
０	名詞,数,*,*,*,*,０,ゼロ,ゼロ
０	名詞,数,*,*,*,*,０,ゼロ,ゼロ
円	名詞,接尾,助数詞,*,*,*,円,エン,エン
です	助動詞,*,*,*,特殊・デス,基本形,です,デス,デス
。	記号,句点,*,*,*,*,。,。,。
EOS
```
Since full-width numbers are registered in the morphological dictionary (IPADIC), each number becomes a separate token, so that a full-width `１０００` cannot be searched for `1000`.

For this reason, it is common for search engines that handle Japanese to perform character normalization before tokenization. Is there a way for Meilisearch to perform character normalization before tokenization?

**Comment by ManyTheFish** [comment]
Hello @mosuka,
Thanks a lot for those precisions!
Unfortunately, it would be a lot of work to invert the process.
For now, we will keep it like this and stick with this issue.
However, I have a similar issue with the Malayalam Language and I'll have to find a way to have both pre-post-normalizers. 🤔

**Comment by charlesschaefer** [comment]
Hey folks, I started trying to implement this issue still during the Hacktober fest. But I couldn't focus so much on it. Then I didn't ever commented here to avoid to "block" an issue that someone could eventually implement faster....

But I kept trying to implement it anyway, just to learn more about rust and charabia engine. 

Well, talking now about the implementation.... I started working on it when we still had to implement `normalize()`. So, I had to change some pieces after the consolidation the team made weeks ago, to use the `CharNormalizer` trait. I think it is ok now, but I'm experiencing some issues when we have the global normalization pipeline (and that's the reason I haven't opened a PR yet - please let me know if you prefer that I open it).

The first one is to understand which `Scripts` should be normalized with `nfkd()`. I [tried to follow ](https://github.com/charlesschaefer/charabia/blob/eb3ef5e7c832354e6cfa8d7ab5df210bfd31abff/src/normalizer/compatibility_decomposition.rs#L29) some other implementations, but I'm not 100% it is ok - so if someone can give me some guidance it would be great :-)

Other and maybe more complex, is that the `LatinNormalizer` uses `deunicode`, which will try to remove the accent marks and remove the characters that it doesn't recognize. So... should we avoid to use `nfkd()` side-by-side with `LatinNormalizer`?

Thanks for your help :-)

**Comment by ManyTheFish** [comment]
Hello @charlesschaefer,
first, don't hesitate to create a PR on this repo, this would be easier for me to guide you in the implementation.
Then, [UnicodeNormalization trait is implemented for any type that implements IntoIter<char>](https://docs.rs/unicode-normalization/0.1.22/unicode_normalization/trait.UnicodeNormalization.html#impl-UnicodeNormalization%3CIntoIter%3Cchar%3E%3E-for-char), this way `Some('a').nfkd()` would give you an iterator over chars, then, [as the Latin normalizer](https://github.com/meilisearch/charabia/blob/3dde30fb75f381ec3155d853699278eddd1934bc/src/normalizer/latin.rs#L18) a match would finally do the job to convert your Iterator into the expected type.
