### ISSUE TITLE
Classify tokens after Segmentation instead of Normalization

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#150]
Classifying tokens after Segmentation instead of Normalization in the tokenization pipeline would enhance the precision of the stop_words classification.
Today, stop words need to be normalized to be properly classified, however, the normalization is more or less lossy and can classy unexpected stop words.
For instance, in French `maïs` (`corn` in 🇬🇧) would be normalized as `mais` (`but` in 🇬🇧), and so, `maïs` will be classified as a stop word if the stop word list contains `mais`.
This would not be possible if the classifier is called before the normalizer.

### Technical approach

Invert the [normalization step and the classification step in the tokenization process](https://github.com/meilisearch/charabia/blob/6d0a01d371088283d4e9bbadba24c0a0d2344571/src/tokenizer.rs#L24-L120)

**Comment by yenwel** [comment]
I'll try this one, anyone else started let me know so I can skip then
