### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by curquiza** [meilisearch/charabia#151]
Checked with @ManyTheFish 

We need to upgrade the dependencies of Charabia for v0.30.0

**Comment by ManyTheFish** [comment]
@curquiza let's delay this task for the next release of Meilisearch, I don't plan to do it for v0.30.0

**Comment by curquiza** [comment]
Hello @ManyTheFish! I suppose this is due to a lack of time during this sprint? Can you confirm since we want to be transparent? 😊

**Comment by ManyTheFish** [comment]
Indeed, I can't be 100% sure about having the time to do it before the pre-release of v0.30.0, moreover, the Hacktoberfest is making a lot of changes in the code and in the dependencies, forcing me to do a final checkout before doing a potential release of Charabia.
I'd prefer to update the dependencies after this checkout.

**Comment by curquiza** [comment]
Got it!
Thanks for letting us know!

**Comment by curquiza** [comment]
@ManyTheFish could we do this for v1.1.0? Related to https://github.com/meilisearch/meilisearch/issues/3285 which is an issue for v1

**Comment by ManyTheFish** [comment]
Yes, I'm doing it this week before releasing a new version of Charabia.

**Comment by ManyTheFish** [comment]
Fixed by #209
