### ISSUE TITLE
Publish hfhchan kvariants wrapper on crates.io

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#184]
Publish t[he rust wrapper](https://github.com/meilisearch/charabia/tree/main/kvariants) around the file kvariant.txt file coming from https://github.com/hfhchan/irg.

- [x] Notify the author (@hfhchan) by e-mail
- [x] Find a proper name for this Library
- [x] Create a CI to publish this new crate on crates.io

**Comment by hfhchan** [comment]
Please go ahead, it's licensed under MIT

My only request is that someone keeps it updated via a GitHub Action or some sort of CI.

**Comment by hfhchan** [comment]
Please also add a message directing people to submit changes to the dictionary to upstream.
