### ISSUE TITLE
Create a CI keeping kvariants up-to-date

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#185]
related to #184

**Comment by goodhoko** [comment]
@ManyTheFish I may give this a shot. 👋 

If I understand the linked discussion correctly, the goal here is to create some sort of CI that will ensure that `kvariants/dictionaries/source/kVariants.tsv` in this repo is kept up to date with `kVariants.txt` in https://github.com/hfhchan/irg, right?

I think we could add a github action that will run on a regular schedule (eg. once a week) that will check if we're up to date. If not, it will submit a PR with the latest changes. This way, you would retain the control over when exactly the update happens.
