### ISSUE TITLE
latin-camelcase feature make wrong segmentation

### ISSUE THREAD

**Issue by hamano** [meilisearch/charabia#289]
The default featre has issue with proper noun segmentation like `OpenSSL`.

main.rs:
```
use std::env;
use charabia::Segment;

fn main() {
    let arg = env::args().nth(1).unwrap();
    let segments = arg.as_str().segment_str().collect::<Vec<&str>>().join("|");
    println!("{}", segments)
}
```

default feature:
```
$ cargo run "OpenSSL OpenSsl openSsl open_ssl"
Open|S|S|L| |Open|Ssl| |open|Ssl| |open|_|ssl
```

disable default feature
```
$ cargo run "OpenSSL OpenSsl openSsl open_ssl"
OpenSSL| |OpenSsl| |openSsl| |open|_|ssl
```

**Comment by ManyTheFish** [comment]
Hello @hamano, What do you expect in terms of segmentation?

Thank you!

**Comment by hamano** [comment]
It is ideal that proper nouns are not split, but if it is not in the dictionary, it can't avoided that `OpenSSL` would be split as `Open|SSL`.
Here, I recognize the issue as splitting it as `Open|S|S|L`. The word `SSL` would disappear.

**Comment by hamano** [comment]
The inability to segment words not found in the dictionary was a characteristic in Japanese. Please ignore that.
In any case, I believe it is desirable that 'OpenSSL' not be segment, even in Latin languages

**Comment by hamano** [comment]
https://github.com/CloudCannon/pagefind/issues/591

**Comment by hamano** [comment]
The word `open_ssl` is not common, but for example, in the case of a module like apache `mod_ssl`, it is expected not to be segmented.

**Comment by ManyTheFish** [comment]
Hello @hamano,
I think the better way to solve this issue is to add the word SSL t[o the tokenizer dictionary](https://docs.rs/charabia/0.8.11/charabia/struct.TokenizerBuilder.html#method.words_dict). It seems to be a specific case more than a generality.

**Comment by hamano** [comment]
I'm concerned not just about the term "OpenSSL" but about countless similar terms.

```
OpenVPN
OpenBSD
OpenJDK
OpenCV
FreeRADIUS
FreeBSD
PostgreSQL
MySQL
MongoDB
```

I don't think all these terms should be added to the dictionary. New terms emerge one after another.

**Comment by hamano** [comment]
If you say this is the expected behavior of the latin-camelcase feature, then that's fine. I'll disable it. However, it's too inconvenient as a default feature, so I reported it, especially for use in technical documentation.

**Comment by ManyTheFish** [comment]
Understood, we may disable it from the default features,
thinking of it, this segmentation is mainly used for the cases you are describing, so if you want to change the behavior of [the segmenter](https://github.com/meilisearch/charabia/blob/c983b9f407837368ac2a70459b6853132b5badf8/charabia/src/segmenter/latin/camel_case.rs#L16-L21), I would gladly accept a new PR.
Moreover, the change seems easy, maybe replacing the highlighted code block by:
```rust
        let should_group = last_char_was_lowercase && char.is_letter_uppercase() {
            false
        } else {
            true
        };

        last_char_was_lowercase = char.is_letter_lowercase();
        should_group
```
Should solve your issue ☺️

**Comment by hamano** [comment]
I am unsure how "OpenSSLError" should be segment. Perhaps in the context of a program constant name appearing in documentation, it is expected not to be segment.
Anyway, I don't understand the use case for the latin-camelcase feature. So, I will simply disable it.
What I wanted to report here is that the excessive segmentation of "OpenSSL" into "Open|S|S|L" is likely not expected by anyone.

**Comment by ManyTheFish** [comment]
Hey @hamano,
no problem. I just wanted to say that if you want to use the feature, you can create a PR enhancing the behavior and I will accept it.
See you!
