### ISSUE TITLE
Handle words containing non-separating dots and coma in Latin tokenization

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#62]
## Summary

Handle `S.O.S` as one word (`S.O.S`) instead of three (`S`, `O`, `S`) or numbers like `3.5` as one word (`3.5`) instead of two (`3`, `5`).

## Explanation

The actual tokenizer considers any `.` or `,` as a hard separator meaning that the two separated words are not considered to be part of the same context.
But there is some exceptions for some words like number that are separated by `.` or `,` but should be considered as one and only one word.

We should modify [the actual latin tokenizer](https://github.com/meilisearch/tokenizer/blob/main/src/tokenizer/legacy_meilisearch.rs) to handle this case.

**Comment by Thearas** [comment]
I like this. Do we also consider `08:00` as one word?

**Comment by ManyTheFish** [comment]
Hello @Thearas!
First of all, I am so sorry to respond only today to your comment. 😖

> I like this. Do we also consider 08:00 as one word?

yes we could, I think we should check, for most of our separators, if the separator is followed by a blank character (space, tab..) before considering that this is the end of the word.

**Comment by Thearas** [comment]
Haha, it's okay~.
I'm curious what is the difference between `UnicodeSegmenter` and `LegacyMeilisearch` usage scenarios? Why not just use `UnicodeSegmenter` (like [Sonic](https://github.com/valeriansaliou/sonic/blob/master/src/lexer/token.rs#L232-L237))? 
@ManyTheFish

**Comment by ManyTheFish** [comment]
Good questions,

> what is the difference between UnicodeSegmenter and LegacyMeilisearch?

We started by implementing our own tokenizer (`LegacyMeilisearch`)  and we discover `UnicodeSegmenter` later, we planned to replace `LegacyMeilisearch` with `UnicodeSegmenter`, but...

> Why not just use UnicodeSegmenter?

`UnicodeSegmenter` is really good and could solve this issue, but after some tests, we discover that it doesn't work as expected for all Latin Languages.
The main one is `French` 🇫🇷:
`UnicodeSegmenter` consider `'` as a non-separator, it works with `English`:
`can't` `shouldn't`... would not be separated and if you search `I can't swim` you are not really interested to find a document that contains `I can swim`. Let's say: it's OK.

But what about `French`?

French don't use `'` for negation contraction but for determiner contraction: for example `l'aventure` (`the adventure`) vs `une aventure` (`an adventure`). Here `UnicodeSegmenter` would consider the two words as different words: `l'aventure` =/= `aventure`
But this is the same word and the same meaning, only the determiner changes.
That's why we delayed the usage of `UnicodeSegmenter`. 🙂

I hope this answers your question. 😊

**Comment by ManyTheFish** [comment]
Hello @WillianBR, thanks for your interest in the tokenizer!
> If I want to build the Meilisarch with UnicodeSegmenter, to test it with my scenary.
 There's a custom build option or I have to change the code?

no, for now, you can't, you will have to wait v0.28 to use `UnicodeSegmenter` 😊

> There's a way I can group text as a string? May be a quote char or anything like that.
All thf tokenizer has a way of group a text and ignore it! Handle it as one pieace!
There's such option on Meilisearch?

I'm not sure to understand, do you mean [phrase search](https://docs.meilisearch.com/learn/what_is_meilisearch/features.html#phrase-search) or something more specific? 🤔
