### ISSUE TITLE
Comment on `Analyzer.analyze` default is out of date

### ISSUE THREAD

**Issue by choznerol** [meilisearch/charabia#82]
https://github.com/meilisearch/tokenizer/blob/1dfc8ad9f5b338c39c3bc5fd5b2d0c1328314ddc/src/analyzer.rs#L300-L301

This default behavior mentioned in the comment seems to have changed in #27 :

```diff
             normalizer: Box::new(IdentityNormalizer),
-            tokenizer: Box::new(UnicodeSegmenter),
+            tokenizer: Box::new(LegacyMeilisearch),
-            normalizer: Box::new(IdentityNormalizer),
+            normalizer: Box::new(normalizer),
```

**Comment by ManyTheFish** [comment]
Hey @choznerol! 
You're right, the documentation is wrong.
I'm currently working on a big refactor (#77) which will completely remove this part of the code,
At the same time, I write a better documentation that will remove this kind of outdated comment.

Thanks for your issue!
