### ISSUE TITLE
Create an issue triage process differencing each tokenizer scopes

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#88]
Create an issue triage process differencing each tokenizer scopes (detector, segmenter, normalizer, classifier)

**Comment by curquiza** [comment]
Check with @ManyTheFish 
Feature requests are done on the product repo
Bugs when using Meilisearch involving the tokenizer -> issue open on Meilisearch's side
Bugs in the charabia library -> issue open in the charabia's side
