### ISSUE TITLE
Disable char map creation for when we don't need it

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/charabia#99]
When we want to index the tokens just to store the words in the inverted index we don't need the char map, maybe we can provide an option to disable creating it.

**Comment by curquiza** [comment]
I put it as good first issue but feel free to ask any questions if you are interested in fixing this. We are aware there is too few information on this issue at the moment, but we are really open to external contributions 😄

**Comment by matthias-wright** [comment]
Is anyone working on this? I would like to give this a try.

**Comment by matthias-wright** [comment]
Hi @ManyTheFish, okay cool! Before I start, I would like to clarify some things.

1. Should I simply add a new method to the Normalizer trait that is called something like `normalize_no_char_map`? I assume that I also should add implementations of this method for LatinNormalizer, ChineseNormalizer, etc.?
2. I will add a new field to the TokenizerBuilder called something like `create_char_map` (bool) and then add a method to set it (like `stop_words`). The default will be true to allow for backwards compatibility. 
3. The same `create_char_map` field is added to Tokenizer. For the `tokenize` method, if the `create_char_map` flag is true, we use `normalize` and if not, we use `normalize_no_char_map`. 

Am I on the right track? :)

**Comment by ManyTheFish** [comment]
Hello @matthias-wright, sorry for the response time.

> In the docstring of Token's [`original_lengths`](https://github.com/meilisearch/charabia/blob/1dcaf3cd872d36ad66be41368ab2a97892980a90/src/token.rs#L128) method, it says that if we call `original_lengths(11)` on the briefcase token in the string "Go💼od", the method will return `(3, 6)`. However, in this snippet:
> 
> ```rust
> use charabia::Tokenize;
> 
> fn main() {
>     let orig = "Go💼od";
>     let mut tokens = orig.tokenize();
>     tokens.next();
>     println!("{:?}", tokens.next().unwrap().original_lengths(11));
> }
> ```
> 
> the output will be `(1, 4)`. Did I confuse something here?

Yes, you are right, the documentation should be updated because the new Latin segmenter behaves differently.
`"Go💼od"`  will now be segmented as  `"go", "💼", "od"`  then normalized  as `"go", "briefcase", "od"`.
For the second token, we return `(1, 4)` meaning 1 character and 4 bytes which corresponds to `💼`

> Hi @ManyTheFish, okay cool! Before I start, I would like to clarify some things.
> 
>     1. Should I simply add a new method to the Normalizer trait that is called something like `normalize_no_char_map`? I assume that I also should add implementations of this method for LatinNormalizer, ChineseNormalizer, etc.?

I think we should add a method named `normalize_with_option` taking a `NormalizerOption` structure in parameter, this would allow us to add new options later without having to break the API. 
Then, as you said, update each `Normalizer` to take into account this option.
 
>     2. I will add a new field to the TokenizerBuilder called something like `create_char_map` (bool) and then add a method to set it (like `stop_words`). The default will be true to allow for backwards compatibility.

Yes! 👍 

>     3. The same `create_char_map` field is added to Tokenizer. For the `tokenize` method, if the `create_char_map` flag is true, we use `normalize` and if not, we use `normalize_no_char_map`.

if you create a `normalize_with_option` method instead, you would always call it passing the `NormalizerOption` structure initialized during the build, what do you think? 🤔

> Am I on the right track? :)

I think so, I'll request changes on your PR if I have other ideas. Don't hesitate to early create a draft!

Thanks for your interest in the project! 😊

**Comment by matthias-wright** [comment]
Hi @ManyTheFish, thanks for the response!

> if you create a normalize_with_option method instead, you would always call it passing the NormalizerOption structure initialized during the build, what do you think? thinking

So something like this?
```rust
let orig = "Go💼od";
let option = NormalizerOption {};
let mut tokens = orig.tokenize(option);
```

Then we don't need the `create_char_map` field for the `TokenizerBuilder`.

**Comment by ManyTheFish** [comment]
> So something like this?
> 
> ```rust
> let orig = "Go💼od";
> let option = NormalizerOption {};
> let mut tokens = orig.tokenize(option);
> ```
> 
> Then we don't need the `create_char_map` field for the `TokenizerBuilder`.

I'd prefer to avoid this, `traits` implemented for `&str` should remain simple, the usage of:

```rust
"hello world".tokenize()
"hello world".segment()
```
should be, in my sense, the default behavior.

If the user wants to have a custom config, he should create his own `Tokenizer` passing by a `TokenizerBuilder`:
```rust
let s = "hello world";

let mut builder = TokenizerBuilder::default();

// allow char_map building
builder.char_map(true);

let tokenizer = builder.build();

let tokens = tokenizer.tokenize(s);
```

What do you think?

**Comment by ManyTheFish** [comment]
fixed by https://github.com/meilisearch/charabia/pull/109
